Traceback (most recent call last):
  File "/Users/leo/Desktop/AML/Multi-GNN/main.py", line 41, in <module>
    main()
  File "/Users/leo/Desktop/AML/Multi-GNN/main.py", line 38, in main
    infer_gnn(tr_data, val_data, te_data, tr_inds, val_inds, te_inds, args, data_config)
  File "/Users/leo/Desktop/AML/Multi-GNN/inference.py", line 64, in infer_gnn
    if not (args.avg_tps or args.finetune):
AttributeError: 'Namespace' object has no attribute 'avg_tps'
